### ISSUE TITLE
Async/sync promises

### ISSUE THREAD

**Issue by pyrsmk** [timjansen/PinkySwear.js#12]
Hi!

I'm the lead developer of [qwest](https://github.com/pyrsmk/qwest) and I've decided to implement PinkySwear for its promises. With ajax, even if it's strongly disencouraged, we can make `sync` requests instead of `async`. But I can't achieve it working as expected since PinkySwear seems to defer the execution of the promises stack.

Is there a way/option to configure that?

Regards

**Comment by timjansen** [comment]
Hi Aurélien,

the promises/a+ spec requires all calls to callbacks to be asynchronous. It
would be relatively easy to change that in PinkySwear - all you have to do
is change the defer() function to call the callback directly. But I think
this is outside of the scope of PinkySwear.

Thanks,

Tim

**Comment by pyrsmk** [comment]
I don't think I can change this function since it's local to PinkySwear. But I can see that there's a verification of the state of a global `setImmediate` variable. Even if this behavior is really weird to me, it seems I can override defer with this, no?

**Comment by timjansen** [comment]
Yes, you'd need to fork the library to change defer().

I wouldn't recommend changing setImmediate() - that could break other
libraries.

Tim

**Comment by pyrsmk** [comment]
Forking is the last thing I want to do because I'm using NPM and need to be up-to-date at any time with the main repo. I need to override `defer` in some cases and then have the `defer` method inside the PinkySwear object. I'll think about that, for the moment I don't know exactly what to do ^^

**Comment by timjansen** [comment]
Would it help to be able to override defer ()? That would be a global
object, thus you couldn't use async.

Tim

**Comment by pyrsmk** [comment]
In fact, I think we shouldn't touch anything. Promises must be async by standard. Sync requests shouldn't be used and they will work even with async promises (but not in a procedural way, as we could expect). I'll add a note in the qwest documentation ^^ Thanks for your help!

**Comment by pyrsmk** [comment]
Otherwise, I'm looking at the current promises implementation of qwest, and it seems some functionnalities would be dropped. Per example : https://github.com/pyrsmk/qwest/issues/22

It's an old issue I fixed, but now I think this behavior is not valid at all (to pass values from a callback to another). What do you think?

**Comment by timjansen** [comment]
You can pass a value.

That's described in 7.ii. of the promises spec and 3.iv./4 of the
resolution procedure:
https://github.com/promises-aplus/promises-spec

Tim

**Comment by pyrsmk** [comment]
As you said in the other issue, promises are terribly complicated. And I surely don't really understand what could be a concrete example of that value passing ;)

**Comment by timjansen** [comment]
What do you mean? If your then() handler returns a value, the promise
returned by then() will be fulfilled.

Tim

**Comment by pyrsmk** [comment]
English is not my native language, so specifications are really complicated to me to understand ^^

So, if I have : 

```js
var a = promise.then(function() {
    return 5;
});
```

Then `a` equals to `5`?

**Comment by timjansen** [comment]
If you just execute this code, you have a new pending promise in *a*. If
you then fulfill the *promise*, e.g. by calling *promise(true)*, the
promise in *a* will be fulfilled. If you then read its values, you will get
5:

var a = promise.then(function() {
    return 5;
});

promise(true); // fulfill promise

a.then(function(val) {

  console.log(a); // prints 5

});


Tim

**Comment by pyrsmk** [comment]
Hum... Is it really `a` that equals to `5` or is it `val`? (that would makes better sense :p )

**Comment by timjansen** [comment]
Sorry, it should be console.log(val).

Tim

**Comment by pyrsmk** [comment]
Ok ;)

So, here's my final question! If we can pass values, only the first `then` callback will receive the variables we have defined with `promise(true, [var1, var2, var3])`, and all the others will have the passed value from the first callback. If no value is returned by a callback, then the passed variables will default to `var1, var2, var3`. Is that right?

**Comment by timjansen** [comment]
Not sure which example you refer to anymore, but if you call promise(true,
[var1, var2...]), only those then() handlers that are directly registered
with the promise will be called with those values. The promises returned by
then() handlers will not get those values. There is no default.

Please note that passing more than one value is a PinkySwear extension.
Other implementations may not offer it.

TIm

**Comment by pyrsmk** [comment]
In fact, I'm not refering to another example. Here's what I wanted to say : 

```js
promise.then(function(var1, var2, var3) {
			return 5;
		})
		.then(function(val) {
			// Prints 5
			console.log(val);
		});

promise(true, [var1, var2, var3]);
```

The first handler receives `var1, var2, var3` and the second one receives `val`, because we override `var1, var2, var3` with a new value. If we had not returned `5` in the first handler, then the second handler should have `var1, var2, var3` passed in the function instead of `val`? (that's what I meant by `default`)

**Comment by timjansen** [comment]
Only if you had no handler. If you have a handle and return no value, the
second promise's value would be undefined.

Tim

**Comment by pyrsmk** [comment]
Again, thanks a lot for have taken the time to explain me how promises are working. This spec is really obscure and weird to me.
