### ISSUE TITLE
Rejected but then promise still called

### ISSUE THREAD

**Issue by pyrsmk** [timjansen/PinkySwear.js#13]
Hi,

I'm testing my library (cf. #12) and I've encountered a weird behavior.

```js
qwest.get('tests/multiple/foo')
	 .then(function(xhr, response){
		++i;
		console.log('bp1');
	 })
	 ['catch'](function(xhr, response, e){
		++j;
		console.log('bp2');
	 })
	 .then(function(xhr, response){
		++i;
		console.log('bp3');
	 })
	 .complete(function(xhr, response){
		++k;
		ok(i==0 && j==1 && k==1, i+'/'+j+'/'+k);
		console.log('bp4');
		start();
	 })
```

I'm testing with QUnit. Qwest makes a call to a non existing page and I'm verifying if the promise implementation is working as expected. Then, only the `catch` and `complete` promises should be called, but it appears the second `then` is called too, although the promise is rejected.

Here's how I have defined the `catch` and `complete` functions : 

```js
promise = pinkySwear(function(set) {
	set['catch'] = function(f) {
		return set.then(null, f);
	};
	set.complete = function(f) {
		return set.then(f, f);
	};
        return set;
});
```

Regards

**Comment by pyrsmk** [comment]
Please not that my qwest calls are nested, then (from my previous example) the one who does not work is the second call nested in the first one.

**Comment by timjansen** [comment]
Not sure the output is, but it seems like you expect the handler to be
invoked because a previous promise in the promise chain has been rejected.
But every then() creates a new promise. So if you have code like:

var promise = pinkySwear();
promise.then(function() { console.log('s1'); }, function() {
console.log('e1'); })
             .then(function() { console.log('s2'); }, function() {
console.log('e2'); });
promise(false);

Then you would expect the output to be 'e1', 'e2', But correct is 'e1',
's2'. Each then() creates a new promise, and as the second promise has not
been rejected, the fulfillment handler is called.


Hope this helps ( and I didn't get anything wrong - promises are terribly
complicated and I get stuff mixed up all the time when I didn't implement
them for a few weeks..)
Tim

**Comment by pyrsmk** [comment]
This helps very much! That explains what it is acting weird...
So... To fix that, I'll need to keep a stack of all the created promises and then fulfill or reject all of them (if I did understand well)

**Comment by timjansen** [comment]
Not sure why you want to do that, but when you want to have two handlers
called when a promise is fulfilled, you need to register them for the same
promise. That's not the case when you just chain then() invocations, as
every then() creates a new promise and returns it.

TIm

**Comment by pyrsmk** [comment]
My god... I'm really lost. To be sure : 

```js
var promise = pinkySwear();
var a = promise.then(function(){ console.log('BP1'); });
var b = promise.then(function(){ console.log('BP2'); });

promise(true);
```

Then, `BP1` and `BP2` would print? Are `a` and `b` the same object?

**Comment by timjansen** [comment]
Yes, BP1 and BP2. But a and b are two different objects (both promises).

Tim

**Comment by pyrsmk** [comment]
So, if I understand well... The first callback prints `BP1` because I fulfilled the promise. And the second callback prints `BP2` because I didn't fulfilled it but it fulfills by default. This is it? ^^

**Comment by timjansen** [comment]
No. You have registered two fulfillment handlers for *promise* and when the
promise has been fulfilled, all fulfillment handlers will be invoked in the
order they have been registered with.

Tim

**Comment by pyrsmk** [comment]
Ok. That makes sense. But now I just wanna die :D 
I can't understand why my code (the very first example of this thread) does not work as expected.

Back to your example with "s1, s2, e1, e2". Why all rejectment handlers are not invoked? While you're saying all fulfillment handlers are invoked if we fulfill the promise, why rejecting does not work the same way?

**Comment by timjansen** [comment]
Cause the first then() returned a new promise, and that has been fulfilled
when the then() callback finished without exception.

Tim

**Comment by pyrsmk** [comment]
Then (still with your example), how can I do to reject the second promise?

**Comment by timjansen** [comment]
Not handle it or throw an exception.

**Comment by pyrsmk** [comment]
Ok, thanks a lot for your explanations, I think I will drop this qwest's unit test because I had just misunderstood how promises should have work.
